# Generated by Django 4.1.5 on 2023-01-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_cart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
