# Generated by Django 4.1.5 on 2023-01-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_total_data_order_vendors"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedfood",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("New", "New"),
                    ("Accepted", "Accepted"),
                    ("Cancelled", "Cancelled"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
