# Generated by Django 4.1.5 on 2023-02-04 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0006_alter_openinghour_options_and_more"),
        ("orders", "0003_orderedfood_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="vendors",
        ),
        migrations.AddField(
            model_name="order",
            name="vendors",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendor.vendor",
            ),
        ),
    ]
