# Generated by Django 4.1.5 on 2023-02-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_order_vendors_order_vendors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="vendors",
            new_name="vendor",
        ),
    ]
